<?php

    $pageTitle = '';
    $home = false;

?>

<!DOCTYPE html>
<html class="not-home">

<?php require 'components/head.phtml'; ?>

<body>

    <?php include 'components/header.phtml' ?>

    <div class="container content">

        <div class="bikes">
            <span class="title-l">My bikes</span>
            <i class="fas fa-close"></i>
            <ul>
                <li class="bike bike-1">
                    <div class="bike__img">
                        <img src="img/fiets1.jpg" alt="">
                    </div>
                    <div class="bike__content">
                        <span class="title-xs">Merida Red</span>
                        <p>02123904</p>
                    </div>
                </li>

                <?php

                if(isset($_COOKIE['new_bike'])):
                    $cookie = json_decode($_COOKIE['new_bike'], true)[0];
                ?>

                    <li class="bike bike-2">
                        <div class="bike__img">
                            <img src="img/fiets2.JPG" alt="">
                        </div>
                        <div class="bike__content">
                            <span class="title-xs"><?php echo $cookie['name']; ?></span>
                            <p><?php echo $cookie['number']; ?></p>
                        </div>
                    </li>

                <?php endif; ?>
                <li class="add-bike">
                    <a class="" href="new_bike.phtml">
                        <i class="fas fa-plus"></i>
                        <span class="">Add new bike</span>
                    </a>
                </li>
            </ul>
        </div>

    </div>

  <?php require 'components/script.phtml'; ?>

</body>

</html>
