<?php

    $pageTitle = '';

?>

<!DOCTYPE html>
<html>

<?php require 'components/head.phtml'; ?>

<body>

    <header>
        <div class="container">

            <div class="logo">
                <img src="" alt="">
            </div>

            <nav>
                <ul class="menu">
                    <li>item 1</li>
                    <li>item 2</li>
                    <li>item 3</li>
                </ul>
            </nav>

        </div>

    </header>

    <div class="container">



    </div>

  <?php require 'components/script.phtml'; ?>

</body>

</html>
