<?php

    $pageTitle = '';
    $home = true;

?>

<!DOCTYPE html>
<html class="home">

<?php require 'components/head.phtml'; ?>

<body>

    <?php include 'components/header.phtml' ?>

    <div class="container content">

        <div class="map-container">
            <div id="map">

            </div>
        </div>

        <div class="right">

            <div class="bikes">
                <span class="title-l">My bikes</span>
                <i class="fas fa-close"></i>
                <ul>
                    <li class="bike bike-1 is_active">
                        <div class="bike__img">
                            <img src="img/fiets1.jpg" alt="">
                        </div>
                        <div class="bike__content">
                            <span class="title-xs">Merida Red</span>
                            <p>02123904</p>
                        </div>
                    </li>
                    <?php

                    if(isset($_COOKIE['new_bike'])):
                        $cookie = json_decode($_COOKIE['new_bike'], true)[0];
                        ?>

                        <li class="bike bike-2">
                            <div class="bike__img">
                                <img src="img/fiets2.JPG" alt="">
                            </div>
                            <div class="bike__content">
                                <span class="title-xs"><?php echo $cookie['name']; ?></span>
                                <p><?php echo $cookie['number']; ?></p>
                            </div>
                        </li>

                    <?php endif; ?>
                    <li class="add-bike">
                        <a class="" href="new_bike.phtml">
                            <i class="fas fa-plus"></i>
                            <span class="">Add new bike</span>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="bike-detail">
                <div class="bike__info">
                    <div class="bike__img">
                        <img src="img/fiets1.jpg" alt="">
                    </div>
                    <div class="bike__content">
                        <span class="title-xs bike__title">Merida Red</span>
                        <p class="bike__number">02123904</p>
                    </div>
                </div>
                <p class="distance"><span>1080</span> meters away from you</p>
                <a class="route button" target="_blank" href="https://www.google.com/maps/place/">Show route</a>
                <div class="close">
                    <i class="fas fa-close"></i>
                </div>
            </div>

        </div>

    </div>

  <?php require 'components/script.phtml'; ?>

</body>

</html>
