<?php

    $pageTitle = '';

?>

<!DOCTYPE html>
<html>

<?php require 'components/head.phtml'; ?>

<body>

    <header>
        <div class="container">

            <div class="logo">
                <span class="title-l">Where's my bike</span>
            </div>

            <nav>
                <ul class="menu">
                    <li>item 1</li>
                    <li>item 2</li>
                    <li>item 3</li>
                </ul>
            </nav>

        </div>

    </header>

    <div class="container content">

        <div class="map-container">
            <div id="map">

            </div>
        </div>

        <div class="right">

            <div class="bikes">
                <span class="title-l">My bikes</span>
                <ul>
                    <li class="bike bike-1 is_active">
                        <div class="bike__img"></div>
                        <div class="bike__content">
                            <span class="title-xs">Merida Red</span>
                            <p>02123904</p>
                        </div>
                    </li>
                    <li class="bike bike-2">
                        <div class="bike__img"></div>
                        <div class="bike__content">
                            <span class="title-xs">Title 2</span>
                            <p>information 2</p>
                        </div>
                    </li>
                    <li class="add-bike">
                        <a class="" href="">
                            <i class="fas fa-plus"></i>
                            <span class="">Add new bike</span>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="bike-detail">
                <div class="bike__info">
                    <div class="bike__img"></div>
                    <div class="bike__content">
                        <span class="title-xs bike__title">Merida Red</span>
                        <p class="bike__number">02123904</p>
                    </div>
                </div>
                <p class="distance"><span>1080</span> meters away from you</p>
                <a class="route button" target="_blank" href="https://www.google.com/maps/place/">Show route</a>
            </div>

        </div>

    </div>

  <?php require 'components/script.phtml'; ?>

</body>

</html>
