<header>
    <div class="container">

        <div class="menu-toggle">
            <i class="fas fa-bars"></i>
            <span>Menu</span>
        </div>

        <div class="logo">
            <span class="title-l">Where's my bike</span>
        </div>

        <div class="bikes-toggle">
            <i class="fas fa-bicycle"></i>
            <span>Bikes</span>
        </div>

        <nav>
            <i class="fas fa-close"></i>
            <ul class="menu">
                <li><a href="index.phtml">Find my bike</a></li>
                <li><a href="">My profile</a></li>
                <li><a href="bikes.phtml">My bikes</a></li>
                <li><a href="login.phtml">Log out</a></li>
            </ul>
        </nav>

    </div>

</header>